source 'https://github.com/Chj1995/FFSpecs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'FFSpecialKit_Category_Example' do
  pod 'FFSpecialKit_Category', :path => '../'

  target 'FFSpecialKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
